[build]
functions = "./functions"

[[redirects]]
from = "dummy/api/*"
to = "/.netlify/functions/dummy/:splat"
status = 200
force = true

[[redirects]]
from = "/3/*"
to = "/:splat"
status = 200
force = true
