
[build]
functions = "./functions"

[[redirects]]
from = "dummy/api/*"
to = "/.netlify/functions/dummy/:splat"
status = 200
force = true

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200
force = true